### ISSUE TITLE
Alright, where is it?

### ISSUE THREAD

**Issue by userse31** [Nanook/NKit#2]
Seriously? No source code after this long?

I don't want to use my windows 10 machine ;(

**Comment by Nanook** [comment]
Discord link in the Wiki, come test v2. Code will be pushed when the v2 beta comes out. If you want nkit 1 code. Check out the NKitv1 repo

**Comment by menosprezzi** [comment]
Man, why did you launched this tool? It has been 3y since then, and there not even a note about it. The WBFS days was so nice before this. Now is a pain. Many rom sites are uploading files in this format and forcing the community to use this tool (which in some ways could be nice). There's no Linux or Mac versions available, the repo has nothing, there is no opensource code (idk why) so there is no way to build myself a linux version. Is a shame that in 2025 many sites keep using this tool.

If you cant maintain it, open it so the community can do the job!

**Comment by cgarz** [comment]
But... there ARE Linux builds, there ARE crapple builds 🤣

Have you actually been without nkit2 for 3 years because you still didn't find the discord invite? 😱. You've really been missing out if so. It's so good.

Builds have been getting published there for over 1000 days now. Like nook said the discord invite is on [the main wiki page](https://github.com/Nanook/NKit/wiki). AFIK the source will be released when it's more stable. But it is definitely being maintained.

**Comment by Joseph-DiGiovanni** [comment]
@Nanook Why did you make a new repo instead of just continuing work in the original one? If v2 is a full rewrite the repo should be called NKit 2 instead of renaming the original repo to v1. As it is this repo is the first to show on google and without prior knowledge it isn't made obvious the v1 repo even exists.

As a side note, would it not be beneficial to have v2 source publicly available for issue tracking and contribution? Beta testing builds through discord for years is sketchy as hell.

Edit: After looking at the commit history of v1 (or lack thereof) I realize you're basically using github as a pastebin for your completed code. I strongly suggest you learn how to use git/github properly.

**Comment by userse31** [comment]
> But... there ARE Linux builds, there ARE crapple builds 🤣
> 
> Have you actually been without nkit2 for 3 years because you still didn't find the discord invite? 😱. You've really been missing out if so. It's so good.
> 
> Builds have been getting published there for over 1000 days now. Like nook said the discord invite is on [the main wiki page](https://github.com/Nanook/NKit/wiki). AFIK the source will be released when it's more stable. But it is definitely being maintained.

Discord is not a source code distribution platform.

**Comment by cgarz** [comment]
> Discord is not a source code distribution platform.

Correct, which is why there is no source code there.

**Comment by cgarz** [comment]
Github releases up, no more douchecord 🥳 
https://github.com/Nanook/NKit/releases/
